"""Define 20 MVP corridors with metadata.

IDs and structure match the frontend convention (data/processed/corridors.json).
Corridors are chosen to cover diverse regions, traffic levels, and bottleneck profiles.
"""
from __future__ import annotations

CORRIDOR_DEFINITIONS: list[dict] = [
    # === ASIA-EUROPE ===
    {
        "corridor_id": "singapore-rotterdam",
        "corridor_name": "Singapore \u2192 Rotterdam",
        "start_port_id": "singapore", "end_port_id": "rotterdam",
        "start_country_code": "SGP", "end_country_code": "NLD",
        "region": "Asia-Europe", "mode": "maritime", "time_period": "2024",
        "description": "The busiest global trade lane connecting Southeast Asia's largest transshipment hub to Europe's primary gateway through the Suez Canal.",
        "strategic_importance_note": "Handles a major share of Asia-Europe container traffic.",
        "geometry": {"type": "LineString", "coordinates": [[103.822,1.264],[80.2,6.8],[55.3,12.8],[32.5,30.0],[15.0,37.5],[4.479,51.922]]},
    },
    {
        "corridor_id": "shanghai-hamburg",
        "corridor_name": "Shanghai \u2192 Hamburg",
        "start_port_id": "shanghai", "end_port_id": "hamburg",
        "start_country_code": "CHN", "end_country_code": "DEU",
        "region": "Asia-Europe", "mode": "maritime", "time_period": "2024",
        "description": "Major Asia-Northern Europe route linking China's largest port to Germany's primary deep-water gateway.",
        "strategic_importance_note": "Critical for German automotive and machinery imports from China.",
        "geometry": {"type": "LineString", "coordinates": [[121.474,31.230],[103.8,1.3],[72.8,10.5],[32.5,30.0],[15.0,37.5],[9.966,53.533]]},
    },
    {
        "corridor_id": "hong_kong-le_havre",
        "corridor_name": "Hong Kong \u2192 Le Havre",
        "start_port_id": "hong_kong", "end_port_id": "le_havre",
        "start_country_code": "HKG", "end_country_code": "FRA",
        "region": "Asia-Europe", "mode": "maritime", "time_period": "2024",
        "description": "Connects Hong Kong's deep-water transshipment hub with France's Atlantic gateway for consumer goods.",
        "strategic_importance_note": "Key route for French luxury goods exports and Chinese electronics imports.",
        "geometry": {"type": "LineString", "coordinates": [[114.169,22.319],[103.8,1.3],[72.8,10.5],[32.5,30.0],[-5.0,48.0],[0.117,49.483]]},
    },
    # === TRANS-PACIFIC ===
    {
        "corridor_id": "shanghai-los_angeles",
        "corridor_name": "Shanghai \u2192 Los Angeles",
        "start_port_id": "shanghai", "end_port_id": "los_angeles",
        "start_country_code": "CHN", "end_country_code": "USA",
        "region": "Trans-Pacific", "mode": "maritime", "time_period": "2024",
        "description": "The dominant trans-Pacific route carrying consumer goods from China to the US West Coast.",
        "strategic_importance_note": "Highest container volume of any trans-Pacific route.",
        "geometry": {"type": "LineString", "coordinates": [[121.474,31.230],[140.0,35.0],[180.0,40.0],[-150.0,38.0],[-118.265,33.740]]},
    },
    {
        "corridor_id": "busan-long_beach",
        "corridor_name": "Busan \u2192 Long Beach",
        "start_port_id": "busan", "end_port_id": "long_beach",
        "start_country_code": "KOR", "end_country_code": "USA",
        "region": "Trans-Pacific", "mode": "maritime", "time_period": "2024",
        "description": "Key Asia-Americas route connecting South Korea's largest port to Long Beach.",
        "strategic_importance_note": "Critical for Korean electronics and automotive exports.",
        "geometry": {"type": "LineString", "coordinates": [[129.040,35.103],[155.0,40.0],[-180.0,43.0],[-150.0,39.0],[-118.217,33.754]]},
    },
    {
        "corridor_id": "kaohsiung-vancouver",
        "corridor_name": "Kaohsiung \u2192 Vancouver",
        "start_port_id": "kaohsiung", "end_port_id": "vancouver",
        "start_country_code": "TWN", "end_country_code": "CAN",
        "region": "Trans-Pacific", "mode": "maritime", "time_period": "2024",
        "description": "Semiconductor and electronics trade route connecting Taiwan's largest port to Canada's Pacific gateway.",
        "strategic_importance_note": "Key corridor for semiconductor supply chain to North America.",
        "geometry": {"type": "LineString", "coordinates": [[120.283,22.617],[140.0,35.0],[170.0,45.0],[-150.0,48.0],[-123.117,49.283]]},
    },
    {
        "corridor_id": "yokohama-los_angeles",
        "corridor_name": "Yokohama \u2192 Los Angeles",
        "start_port_id": "yokohama", "end_port_id": "los_angeles",
        "start_country_code": "JPN", "end_country_code": "USA",
        "region": "Trans-Pacific", "mode": "maritime", "time_period": "2024",
        "description": "Japan-US trade corridor for automotive parts, machinery, and manufactured goods.",
        "strategic_importance_note": "Dominant route for Japanese automotive exports to North America.",
        "geometry": {"type": "LineString", "coordinates": [[139.65,35.444],[155.0,40.0],[-180.0,42.0],[-150.0,38.0],[-118.265,33.740]]},
    },
    # === REGIONAL ASIA ===
    {
        "corridor_id": "jebel_ali-mumbai",
        "corridor_name": "Jebel Ali \u2192 Mumbai",
        "start_port_id": "jebel_ali", "end_port_id": "mumbai",
        "start_country_code": "ARE", "end_country_code": "IND",
        "region": "Regional", "mode": "maritime", "time_period": "2024",
        "description": "High-intensity regional corridor connecting the UAE's premier port to India's busiest container terminal.",
        "strategic_importance_note": "Handles significant container and petroleum traffic across the Arabian Sea.",
        "geometry": {"type": "LineString", "coordinates": [[55.061,25.018],[62.0,22.0],[69.0,20.0],[72.952,18.949]]},
    },
    {
        "corridor_id": "singapore-port_klang",
        "corridor_name": "Singapore \u2192 Port Klang",
        "start_port_id": "singapore", "end_port_id": "port_klang",
        "start_country_code": "SGP", "end_country_code": "MYS",
        "region": "Regional", "mode": "maritime", "time_period": "2024",
        "description": "Short-haul Strait of Malacca feeder connecting the world's busiest transshipment hub to Malaysia's largest port.",
        "strategic_importance_note": "Critical feeder route through the world's busiest shipping strait.",
        "geometry": {"type": "LineString", "coordinates": [[103.85,1.283],[102.5,2.0],[101.4,3.0]]},
    },
    {
        "corridor_id": "laem_chabang-hai_phong",
        "corridor_name": "Laem Chabang \u2192 Hai Phong",
        "start_port_id": "laem_chabang", "end_port_id": "hai_phong",
        "start_country_code": "THA", "end_country_code": "VNM",
        "region": "Regional", "mode": "maritime", "time_period": "2024",
        "description": "Intra-ASEAN manufacturing corridor linking Thailand's industrial port to Vietnam's northern gateway.",
        "strategic_importance_note": "Growing corridor driven by supply chain diversification from China.",
        "geometry": {"type": "LineString", "coordinates": [[100.883,13.083],[104.0,10.0],[106.7,10.8],[106.667,20.867]]},
    },
    {
        "corridor_id": "colombo-singapore",
        "corridor_name": "Colombo \u2192 Singapore",
        "start_port_id": "colombo", "end_port_id": "singapore",
        "start_country_code": "LKA", "end_country_code": "SGP",
        "region": "Regional", "mode": "maritime", "time_period": "2024",
        "description": "Indian Ocean transshipment corridor connecting Sri Lanka's hub to Singapore.",
        "strategic_importance_note": "Key relay point for India-bound and East Africa-bound cargo.",
        "geometry": {"type": "LineString", "coordinates": [[79.85,6.933],[85.0,5.0],[95.0,3.0],[103.85,1.283]]},
    },
    # === ATLANTIC ===
    {
        "corridor_id": "algeciras-santos",
        "corridor_name": "Algeciras \u2192 Santos",
        "start_port_id": "algeciras", "end_port_id": "santos",
        "start_country_code": "ESP", "end_country_code": "BRA",
        "region": "Atlantic", "mode": "maritime", "time_period": "2024",
        "description": "Europe-South America trade link for agricultural products and manufactured goods.",
        "strategic_importance_note": "Key route for Brazilian commodity exports to Europe.",
        "geometry": {"type": "LineString", "coordinates": [[-5.443,36.128],[-18.0,22.0],[-28.0,5.0],[-40.0,-18.0],[-46.334,-23.961]]},
    },
    {
        "corridor_id": "houston-rotterdam",
        "corridor_name": "Houston \u2192 Rotterdam",
        "start_port_id": "houston", "end_port_id": "rotterdam",
        "start_country_code": "USA", "end_country_code": "NLD",
        "region": "Atlantic", "mode": "maritime", "time_period": "2024",
        "description": "Major energy and bulk commodity corridor connecting the US Gulf petrochemical complex with Europe.",
        "strategic_importance_note": "Dominant route for US LNG and refined petroleum exports to Europe.",
        "geometry": {"type": "LineString", "coordinates": [[-95.283,29.75],[-85.0,25.0],[-30.0,40.0],[4.483,51.9]]},
    },
    {
        "corridor_id": "southampton-montreal",
        "corridor_name": "Southampton \u2192 Vancouver",
        "start_port_id": "southampton", "end_port_id": "vancouver",
        "start_country_code": "GBR", "end_country_code": "CAN",
        "region": "Atlantic", "mode": "maritime", "time_period": "2024",
        "description": "UK-Canada trade corridor through the North Atlantic and Panama Canal.",
        "strategic_importance_note": "Key corridor for UK-Canada bilateral trade.",
        "geometry": {"type": "LineString", "coordinates": [[-1.4,50.9],[-20.0,50.0],[-50.0,40.0],[-80.0,20.0],[-79.5,9.0],[-100.0,15.0],[-123.117,49.283]]},
    },
    # === MEDITERRANEAN / MIDDLE EAST ===
    {
        "corridor_id": "piraeus-istanbul",
        "corridor_name": "Piraeus \u2192 Istanbul",
        "start_port_id": "piraeus", "end_port_id": "istanbul",
        "start_country_code": "GRC", "end_country_code": "TUR",
        "region": "Mediterranean", "mode": "maritime", "time_period": "2024",
        "description": "Short-haul Eastern Mediterranean route linking Greece's main port to Turkey's commercial hub.",
        "strategic_importance_note": "Critical for Aegean Sea trade and Black Sea access.",
        "geometry": {"type": "LineString", "coordinates": [[23.635,37.943],[25.0,38.0],[26.5,39.0],[28.967,41.017]]},
    },
    {
        "corridor_id": "jeddah-alexandria",
        "corridor_name": "Jeddah \u2192 Alexandria",
        "start_port_id": "jeddah", "end_port_id": "alexandria",
        "start_country_code": "SAU", "end_country_code": "EGY",
        "region": "Mediterranean", "mode": "maritime", "time_period": "2024",
        "description": "Red Sea to Mediterranean corridor through the Suez Canal linking Saudi Arabia and Egypt.",
        "strategic_importance_note": "Strategic Suez Canal transit corridor for Middle East-Mediterranean trade.",
        "geometry": {"type": "LineString", "coordinates": [[39.183,21.517],[38.0,25.0],[33.0,28.0],[32.55,29.967],[32.3,31.3],[29.833,31.167]]},
    },
    # === AFRICA ===
    {
        "corridor_id": "durban-singapore",
        "corridor_name": "Durban \u2192 Singapore",
        "start_port_id": "durban", "end_port_id": "singapore",
        "start_country_code": "ZAF", "end_country_code": "SGP",
        "region": "Indian Ocean", "mode": "maritime", "time_period": "2024",
        "description": "Long-haul Indian Ocean corridor connecting Southern Africa's busiest port to Asia's transshipment hub.",
        "strategic_importance_note": "Key route for South African mineral and agricultural exports to Asia.",
        "geometry": {"type": "LineString", "coordinates": [[31.033,-29.867],[45.0,-15.0],[60.0,-5.0],[80.0,3.0],[103.85,1.283]]},
    },
    # === OCEANIA ===
    {
        "corridor_id": "melbourne-yokohama",
        "corridor_name": "Melbourne \u2192 Yokohama",
        "start_port_id": "melbourne", "end_port_id": "yokohama",
        "start_country_code": "AUS", "end_country_code": "JPN",
        "region": "Asia-Pacific", "mode": "maritime", "time_period": "2024",
        "description": "Australia-Japan trade corridor for LNG, iron ore, and coal.",
        "strategic_importance_note": "Critical energy supply corridor for Japan's resource imports.",
        "geometry": {"type": "LineString", "coordinates": [[144.95,-37.817],[150.0,-30.0],[155.0,-20.0],[145.0,0.0],[135.0,20.0],[139.65,35.444]]},
    },
    {
        "corridor_id": "melbourne-shanghai",
        "corridor_name": "Melbourne \u2192 Shanghai",
        "start_port_id": "melbourne", "end_port_id": "shanghai",
        "start_country_code": "AUS", "end_country_code": "CHN",
        "region": "Asia-Pacific", "mode": "maritime", "time_period": "2024",
        "description": "Australia-China bulk commodity corridor for iron ore, coal, and agricultural products.",
        "strategic_importance_note": "Largest bilateral commodity trade route in the Asia-Pacific.",
        "geometry": {"type": "LineString", "coordinates": [[144.95,-37.817],[150.0,-25.0],[145.0,-10.0],[130.0,5.0],[121.474,31.230]]},
    },
    # === INTRA-ASIA FEEDER ===
    {
        "corridor_id": "tanjung_pelepas-hong_kong",
        "corridor_name": "Tanjung Pelepas \u2192 Hong Kong",
        "start_port_id": "tanjung_pelepas", "end_port_id": "hong_kong",
        "start_country_code": "MYS", "end_country_code": "HKG",
        "region": "Regional", "mode": "maritime", "time_period": "2024",
        "description": "South China Sea feeder linking Malaysia's fast-growing transshipment port to Hong Kong.",
        "strategic_importance_note": "Growing alternative to Singapore for Southeast Asia-China feeder traffic.",
        "geometry": {"type": "LineString", "coordinates": [[103.55,1.367],[105.0,3.0],[110.0,10.0],[114.169,22.319]]},
    },
]

# Port ID to OECD country code mapping
PORT_COUNTRY_MAP: dict[str, str] = {
    "singapore": "SGP", "rotterdam": "NLD", "shanghai": "CHN",
    "los_angeles": "USA", "jebel_ali": "ARE", "mumbai": "IND",
    "santos": "BRA", "busan": "KOR", "long_beach": "USA", "algeciras": "ESP",
    "yokohama": "JPN", "melbourne": "AUS", "port_klang": "MYS",
    "hong_kong": "HKG", "hamburg": "DEU", "southampton": "GBR",
    "le_havre": "FRA", "vancouver": "CAN", "istanbul": "TUR",
    "durban": "ZAF", "piraeus": "GRC", "kaohsiung": "TWN",
    "hai_phong": "VNM", "laem_chabang": "THA", "colombo": "LKA",
    "jeddah": "SAU", "houston": "USA", "alexandria": "EGY",
    "tanjung_pelepas": "MYS",
}
